### ISSUE TITLE
History of the project / repo

### ISSUE THREAD

**Issue by jnak** [ardatan/schema-stitching#111]
Hi,

I noticed that the repo was created in early 2023 and none of the git history of the original codebase was imported. That means there is a lot of context lost around the git history and the previous issue tracker. Is there way to find that history? Without this, it looks a bit like the project is no longer maintained, since it's not very active.

Best!

**Comment by jnak** [comment]
The reason I'm asking is that was a lot of issues and complains about this project last time I checked (back in 2017/18). I'm curious to see if those errors still stand or if they have been addressed since then.

**Comment by ardatan** [comment]
The implementation is still under GraphQL Tools repository;
https://github.com/ardatan/graphql-tools
This `schema-stitching` repo has been created after we decided to have a seperate documentation website with various examples.
Maybe we can copy the code from there to this repository in the future.
Also the issues and PRs can be copied??? Not sure if all these are possible.
But still we cannot basically copy the whole history of GraphQL Tools because GraphQL Tools has more stuff not only stitching.

**Comment by jnak** [comment]
Got it! Apologies for the confusion. I thought that was the main repo.
